---
title: "Week_4_CASA_Homework"
output: html_document
date: "2024-10-27"
---
This is the library section
```{r}
library(usethis)
library("sf")
library("tmap")
library("raster")
library("sp")
library(dplyr)
library(here)
install.packages("countrycode")
```

This is the loading the data section

```{r}
geojson_Data<-st_read(here::here("World_Countries_(Generalized)_9029012925078512962.geojson"))
gender_inequality_data<-read.csv("HDR23-24_Composite_indices_complete_time_series.csv")
View(geojson_Data)
```
This is the cleaning the data section
```{r}
gender_inequality_data_clean<-gender_inequality_data%>%
  select(1:38)
gender_inequality_data_clean<-gender_inequality_data_clean%>%
  mutate(hdi_diff=hdi_2019-hdi_2010, iso2=countrycode::countrycode(iso3, origin = 'iso3c', destination = 'iso2c'))%>%
  select(iso2,everything(), -iso3)
gender_inequality_data_clean<-gender_inequality_data_clean%>%
  filter(!is.na(iso2))

```

Merging the Data
```{r}
final_dataset<-gender_inequality_data_clean%>%
  left_join(geojson_Data,by=c("iso2"="ISO"))
final_dataset_clean<-final_dataset%>%
  filter(!is.na(geometry))
```
Clean Data
```{r}
final_dataset_sf<-st_as_sf(final_dataset_clean,crs = 4326)
final_dataset_sf1<-final_dataset_sf%>%
  filter(!is.na(hdi_diff) & !st_is_empty(geometry))
```
Plotting
```{r}
tmap_mode("view")
tm_shape(final_dataset_sf1)+ tm_polygons("hdi_diff", title="Gender Inequality Data Difference between 2010 and 2019", palette = "RdYlGn", style="jenks",alpha = 0.8)+ tm_basemap(server="OpenStreetMap")+
  tm_compass(position = c("left", "bottom"),type="arrow")+
  tm_scale_bar(position = c("left", "bottom"))+ tm_view(view.legend.position = c("right", "bottom"))
```

```{r}
hi randy, its zainab! I tried to run your code but my world data is a shp not geojason... change it now - joking!
```

